---
- name: Install speedtest packages
  ansible.builtin.apt:
    pkg:
      - speedtest-cli

- name: Script_exporter | Install speedtest-exporter
  ansible.builtin.copy:
    src: speedtest-exporter
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0755'

- name: Script_exporter | Remove old speedtest binary (TODO remove)
  ansible.builtin.file:
    path: /usr/local/bin/speedtest
    state: absent