---
image:
  build: false
  upstream:
    source: github
    user: postgres
    repo: posrgres
    type: archive
    format: tar.gz
    file: VERSION.FORMAT
    os: linux
  labels: {}
  name: postgresql
