---
- name: Get upstream version
  ansible.builtin.include_role:
    name: upstream
    tasks_from: "{{ image.upstream.source }}"

- name: Set custom variables
  ansible.builtin.set_fact:
    image_version: "{{ (latest_version | split('-'))[0] }}"
    image_name: "{{ image.name }}"
    image_labels: "{{ image.labels }}"
    image_build: "{{ image.build }}"

- name: End playbook if no new version
  ansible.builtin.meta: end_host
  when: softwares[image.name] is defined and softwares[image.name].version == image_version

- name: Copy boilerplate configuration snippets files
  ansible.builtin.copy:
    src: nginx
    dest: "{{ build_work_dir }}/"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Copy default index file
  ansible.builtin.copy:
    src: index.html
    dest: "{{ build_work_dir }}/index.html"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: Copy dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ build_work_dir }}/Dockerfile"
    mode: '0644'
