---
collections:
  - name: cloud.terraform
    version: 4.0.0
  - name: community.general
    version: 12.0.1
  - name: community.docker
    version: 5.0.1
  - name: community.postgresql
    version: 4.1.0
  - name: ansible.eda
    version: 2.10.0
