---
image:
  build: true
  forkable: true
  upstream:
    source: apk
    repository: main
    package: nodejs
  labels: {}
  name: nodejs
  origin: alpine:latest
  dependances:
    - nodejs
    - npm
